import Head from 'next/head'

import Footer from '../Components/Footer'

import Links from '../Components/Links/Links'


export default function Home() {
  return (
    <div className="flex-col justify-center align-center">
      <Head>
        <title>Sistema de rotas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-col justify-center align-center m-10">
        <h1 className="text-3xl font-bold  text-center text-pink-900">
        Sistema de Rotas
        </h1>

        <p class="text-lg font-light leading-relaxed mt-6 mb-4 text-pink-800 text-center">
        Esse é um exemplo de como as rotas do Next Js funcionam
      </p>

      <Links
      addressRef="/About"
      description = "Este é um link para : Sobre nós"
      />
        <Links
      addressRef="/Contacts"
      description = "Este é um link para : Contatos"
      />
      </main>
      <footer>
        <Footer/>
      </footer>

    
    </div>
  )
}
